// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppConfigure: typeof import('./../src/components/Application/AppConfigure.vue')['default']
    AppDarkModeToggle: typeof import('./../src/components/Application/AppDarkModeToggle.vue')['default']
    AppLocalePicker: typeof import('./../src/components/Application/AppLocalePicker.vue')['default']
    AppLogo: typeof import('./../src/components/Application/AppLogo.vue')['default']
    BasicForm: typeof import('./../src/components/Form/src/BasicForm.vue')['default']
    BasicModal: typeof import('./../src/components/Modal/src/basicModal.vue')['default']
    BasicTable: typeof import('./../src/components/Table/src/BasicTable.vue')['default']
    CardGrid: typeof import('./../src/components/Card/CardGrid.vue')['default']
    CardGridItem: typeof import('./../src/components/Card/CardGridItem.vue')['default']
    CollapseCard: typeof import('./../src/components/Card/CollapseCard.vue')['default']
    CollapseCard_legacy: typeof import('./../src/components/Card/CollapseCard_legacy.vue')['default']
    ColumnSetting: typeof import('./../src/components/Table/src/components/settings/ColumnSetting.vue')['default']
    CountButton: typeof import('./../src/components/CountDown/CountButton.vue')['default']
    CountdownInput: typeof import('./../src/components/CountDown/CountdownInput.vue')['default']
    CountTo: typeof import('./../src/components/CountTo/CountTo.vue')['default']
    EditableCell: typeof import('./../src/components/Table/src/components/editable/EditableCell.vue')['default']
    Icon: typeof import('./../src/components/Icon/Icon.vue')['default']
    Loading: typeof import('./../src/components/Loading/src/Loading.vue')['default']
    LoadingCard: typeof import('./../src/components/Card/LoadingCard.vue')['default']
    PageFooter: typeof import('./../src/components/Page/PageFooter.vue')['default']
    PageWrapper: typeof import('./../src/components/Page/PageWrapper.vue')['default']
    PopConfirmWrapper: typeof import('./../src/components/Table/src/components/actions/popConfirmWrapper.vue')['default']
    ScrollContainer: typeof import('./../src/components/ScrollContainer/ScrollContainer.vue')['default']
    TableAction: typeof import('./../src/components/Table/src/components/actions/TableAction.vue')['default']
    Time: typeof import('./../src/components/Time/index.vue')['default']
  }
}

export { }
